#!/usr/bin/env bash

# Temperature for night mode
TEMP=4500

# Check if hyprsunset is already running
if pgrep -x "hyprsunset" >/dev/null; then
    # Turn off nightlight
    pkill hyprsunset
    notify-send "Nightlight Off" "Color temperature restored to normal."
else
    # Turn on nightlight with desired warmth
    hyprsunset --temperature "$TEMP" &
    notify-send "Nightlight On" "Warm color temperature set to ${TEMP}K."
fi

