#################
### AUTOSTART ###
#################

#exec-once = hyprpanel
#exec-once = waybar &
exec-once = dms run
#exec-once = dunst
#exec-once = dunst &
#exec = ~/.config/hypr/scripts/next-wallpaper.sh
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = wl-paste --type text --watch cliphist store
# Nvidia-specific (current GPU)
exec-once = nvidia-settings --load-config-only
exec-once = nvidia-persistenced

# For Intel GPU (uncomment if switching)
# exec-once = intel-gpu-top  # Optional for monitoring

# For AMD GPU (uncomment if switching)
# exec-once = corectrl  # For GPU control, if installed
# exec-once = nm-applet &
# exec-once = hyprpaper &
# exec-once = firefox &

