#################
### AUTOSTART ###
#################

exec-once = waybar &
exec = ~/.config/hypr/scripts/next-wallpaper.sh
# exec-once = nm-applet &
# exec-once = hyprpaper &
# exec-once = firefox &

