###############################################
#  H Y P R L A N D   M A I N   C O N F I G
#  Modular setup - clean and organized
###############################################

# Source modular configs
source = /home/yhwach/.config/hypr/config/monitors.conf
source = /home/yhwach/.config/hypr/config/env.conf
source = /home/yhwach/.config/hypr/config/appearance.conf
source = /home/yhwach/.config/hypr/config/input.conf
source = /home/yhwach/.config/hypr/config/binding.conf
source = /home/yhwach/.config/hypr/config/rules.conf
source = /home/yhwach/.config/hypr/config/misc.conf
source = /home/yhwach/.config/hypr/autostart.conf

