source = ~/.config/hypr/noctalia/noctalia-colors.conf

source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/environment.conf
source = ~/.config/hypr/config/input.conf
source = ~/.config/hypr/config/appearance.conf
source = ~/.config/hypr/config/layout.conf
source = ~/.config/hypr/config/keybindings.conf
source = ~/.config/hypr/config/rules.conf
source = ~/.config/hypr/config/misc.conf