$activeBorderColor = rgba(8aadf4ee) rgba(b7bdf8ee) 45deg
$inactiveBorderColor = rgba(595959aa)

general {
    gaps_in = 5
    gaps_out = 15
    border_size = 2
    # Border colors defined in noctalia-colors.conf for dynamic theming
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = false
    active_opacity = 0.95
    inactive_opacity = 0.8
    shadow {
        enabled = true
        range = 2
        render_power = 3
        color = rgba(1a1a1aee)
    }
}

animations {
    enabled = yes
    bezier = easeOutQuint,0.23,1,0.32,1
    bezier = quick,0.15,0,0.1,1
    animation = global, 1, 10, default
    animation = windows, 1, 4.79, easeOutQuint
    animation = windowsIn, 1, 4.1, easeOutQuint, popin 87%
    animation = fade, 1, 3.03, quick
    animation = workspaces, 0, 0, ease
}
