#############
### MISC ####
#############

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = true
    vfr = true  # Variable frame rate, recommended for Nvidia; set to false for Intel/AMD
}

