#############
### MISC ####
#############

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = true
    disable_splash_rendering = true
    focus_on_activate = true
    vfr = true  # Variable frame rate, recommended for Nvidia; set to false for Intel/AMD
    vrr = 0     # Disable VRR for NVIDIA to prevent issues; set to 1 for AMD
}

