##############################
### WINDOWS AND WORKSPACES ###
##############################

# Better PiP rules (works for Firefox, Chrome, etc.)
windowrulev2 = float, title:^(Picture-in-Picture|Pip)$
windowrulev2 = pin, title:^(Picture-in-Picture|Pip)$
windowrulev2 = keepaspectratio, title:^(Picture-in-Picture|Pip)$
windowrulev2 = size 15%, title:^(Picture-in-Picture|Pip)$
windowrulev2 = move 75% 65%, title:^(Picture-in-Picture|Pip)$
windowrulev2 = noshadow, title:^(Picture-in-Picture|Pip)$

# Ignore maximize requests
windowrulev2 = suppressevent maximize, class:.*

# Fix XWayland drag issues
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
