[colors]
base = #1e1e2e
mantle = #181825
crust = #11111b
text = #cdd6f4
subtext0 = #a6adc8
subtext1 = #bac2de
surface0 = #313244
surface1 = #45475a
surface2 = #585b70
overlay0 = #6c7086
overlay1 = #7f849c
overlay2 = #9399b2
blue = #89b4fa
lavender = #b4befe
sapphire = #74c7ec
sky = #89dceb
teal = #94e2d5
green = #a6e3a1
yellow = #f9e2af
peach = #fab387
maroon = #eba0ac
red = #f38ba8
mauve = #cba6f7
pink = #f5c2e7
flamingo = #f2cdcd
rosewater = #f5e0dc
transparent = #00000000


;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================


[bar/toph]
monitor = ${env:MONITOR:}
width = 100%
height = 25pt
radius = 0
background = ${colors.base}
foreground = ${colors.text}
bottom = false
line-size = 8pt
border-size = 4pt
border-color = #00000000
padding-left = 5
padding-right = 5
module-margin = 1
separator = |
separator-foreground = ${colors.flamingo}
font-0 = "JetBrainsMono Nerd Font:style=Medium:size=11"
modules-left = rofi_powermenu i3 xwindow
modules-center = date
modules-right = pulseaudio battery brightness redshift cpu gpu_usage wifi_click bluetooth_click
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true


;==========================================================
[module/ss]
type = custom/text
content = " "
content-foreground = ${colors.base}
content-background = ${colors.base}


;==========================================================
[module/i3]
type = internal/i3
enable-scroll = false
show-urgent = true
strip-wsnumbers = true
index-sort = true
enable-click = true
fuzzy-match = true

ws-icon-0 = 1;󰈹
ws-icon-1 = 2;󰡨
ws-icon-2 = 3;
ws-icon-3 = 4;󰓓
ws-icon-4 = 5;󰙯
ws-icon-5 = 6;
ws-icon-6 = 7;
ws-icon-7 = 8;
ws-icon-8 = 9;
ws-icon-9 = 0;


format = <label-state> <label-mode>
label-mode = %mode%
label-mode-padding = 1
label-mode-background = ${colors.red}
label-mode-foreground = ${colors.text}

label-focused = %icon%
label-focused-font = 5
label-focused-foreground = ${colors.yellow}
label-focused-background = ${colors.base}
label-focused-padding = 2

label-unfocused = %icon%
label-unfocused-font = 5
label-unfocused-foreground = ${colors.overlay1}
label-unfocused-background = ${colors.base}
label-unfocused-padding = 2

label-visible = %icon%
label-visible-font = 5
label-visible-foreground = ${colors.subtext0}
label-visible-background = ${colors.base}
label-visible-padding = 2

label-urgent = %icon%
label-urgent-font = 5
label-urgent-foreground = ${colors.red}
label-urgent-background = ${colors.base}
label-urgent-padding = 2

label-separator = ""
label-separator-padding = 0
label-separator-foreground = ${colors.transparent}


;==========================================================
[module/xwindow]
type = internal/xwindow
format-prefix = "    "
format-prefix-foreground = ${colors.overlay1}
format-prefix-background = ${colors.base}
label = %class%
label-maxlen = 60
label-foreground = ${colors.subtext1}
label-background = ${colors.base}
label-padding-left = 2
label-padding-right = 2


;==========================================================
[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = "  "
format-volume-prefix-foreground = ${colors.blue}
format-volume = <label-volume>

label-volume = %percentage%%
label-volume-foreground = ${colors.text}
label-volume-background = ${colors.base}
label-volume-padding-left = 1
label-volume-padding-right = 1

format-muted-prefix = "  "
format-muted-foreground = ${colors.peach}

label-muted = muted
label-muted-foreground = ${colors.peach}
label-muted-background = ${colors.base}
label-muted-padding-left = 1
label-muted-padding-right = 1


;==========================================================
[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%


;==========================================================
[module/brightness]
type = custom/script
exec = ~/.config/polybar/scripts/get-brightness.sh
interval = 5
click-left = ~/.config/polybar/scripts/rofi-brightness-wrapper.sh
click-right = brightnessctl -d intel_backlight set +5%
click-middle = brightnessctl -d intel_backlight set 5%-
label-foreground = ${colors.yellow}
label-font = 0


;==========================================================
[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.rosewater}
label = %percentage:2%%
label-foreground = ${colors.rosewater}


;==========================================================
[module/gpu_usage]
type = custom/script
exec = bash ~/.config/polybar/scripts/gpu_usage.sh
interval = 1
label-foreground = ${colors.rosewater}
label-font = 0


;==========================================================
[module/battery]
type = internal/battery
battery = BAT1
adapter = ACAD
poll-interval = 5
time-format = %H:%M

format-charging = <animation-charging> <label-charging>
format-charging-foreground = ${colors.green}
label-charging = %percentage%%
label-charging-foreground = ${colors.text}
label-charging-background = ${colors.base}
label-charging-padding-left = 1
label-charging-padding-right = 1

format-discharging = <ramp-capacity> <label-discharging>
format-discharging-foreground = ${colors.yellow}
label-discharging = %percentage%%
label-discharging-foreground = ${colors.text}
label-discharging-background = ${colors.base}
label-discharging-padding-left = 1
label-discharging-padding-right = 1

format-full-prefix = "  "
format-full-foreground = ${colors.teal}
label-full = %percentage%%
label-full-foreground = ${colors.text}
label-full-background = ${colors.base}
label-full-padding-left = 1
label-full-padding-right = 1

label-low = [ BATTERY LOW ] %percentage%%
label-low-foreground = ${colors.crust}
label-low-background = ${colors.red}
label-low-padding-left = 1
label-low-padding-right = 1

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

ramp-capacity-0-padding = 1
ramp-capacity-1-padding = 1
ramp-capacity-2-padding = 1
ramp-capacity-3-padding = 1
ramp-capacity-4-padding = 1

ramp-capacity-0-foreground = ${colors.red}
ramp-capacity-1-foreground = ${colors.yellow}
ramp-capacity-2-foreground = ${colors.yellow}
ramp-capacity-3-foreground = ${colors.green}
ramp-capacity-4-foreground = ${colors.green}

ramp-capacity-0-background = ${colors.base}
ramp-capacity-1-background = ${colors.base}
ramp-capacity-2-background = ${colors.base}
ramp-capacity-3-background = ${colors.base}
ramp-capacity-4-background = ${colors.base}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750

animation-charging-0-padding = 1
animation-charging-1-padding = 1
animation-charging-2-padding = 1
animation-charging-3-padding = 1
animation-charging-4-padding = 1

animation-charging-0-foreground = ${colors.green}
animation-charging-1-foreground = ${colors.green}
animation-charging-2-foreground = ${colors.green}
animation-charging-3-foreground = ${colors.green}
animation-charging-4-foreground = ${colors.green}

animation-charging-0-background = ${colors.base}
animation-charging-1-background = ${colors.base}
animation-charging-2-background = ${colors.base}
animation-charging-3-background = ${colors.base}
animation-charging-4-background = ${colors.base}

animation-discharging-0 = [  ]
animation-discharging-1 = [  ]
animation-discharging-2 = [  ]
animation-discharging-3 = [  ]
animation-discharging-4 = [  ]
animation-discharging-framerate = 500

animation-discharging-0-padding = 1
animation-discharging-1-padding = 1
animation-discharging-2-padding = 1
animation-discharging-3-padding = 1
animation-discharging-4-padding = 1

animation-discharging-0-foreground = ${colors.text}
animation-discharging-1-foreground = ${colors.text}
animation-discharging-2-foreground = ${colors.text}
animation-discharging-3-foreground = ${colors.text}
animation-discharging-4-foreground = ${colors.text}

animation-discharging-0-background = ${colors.yellow}
animation-discharging-1-background = ${colors.yellow}
animation-discharging-2-background = ${colors.yellow}
animation-discharging-3-background = ${colors.yellow}
animation-discharging-4-background = ${colors.yellow}


;==========================================================
[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = 睊 Disconnected
label-disconnected-foreground = ${colors.disabled}


;==========================================================
[module/redshift]
type = custom/text
format = 
click-left = ~/.config/polybar/scripts/redshift-rofi.sh
format-foreground = ${colors.maroon}


;==========================================================
[module/bluetooth_click]
type = custom/script
exec = ~/.config/polybar/scripts/bluetooth-device-name.sh
interval = 10
click-left = ~/.config/polybar/scripts/rofi-bluetooth-menu.sh
label-foreground = ${colors.teal}


;==========================================================
[module/wifi_click]
type = custom/script
exec = bash -c 'iwgetid -r | echo ""'
interval = 10
click-left = ~/.config/polybar/scripts/rofi-wifi-menu.sh
label-foreground = ${colors.sky}
label-font = 0


;==========================================================
[module/eth]
inherit = network-base
interface-type = wired
label-connected = 󰈁 %local_ip%


;==========================================================
[module/date]
type = internal/date
interval = 1
fixed-center = true
date =  %A, %b %d  |    %I:%M %p
date-alt =  %A, %B %d, %Y  |   %I:%M:%S %p
label = %date%
label-padding = 2
label-foreground = ${colors.lavender}


;==========================================================
[settings]
screenchange-reload = true
pseudo-transparency = true


;==========================================================
[module/rofi_powermenu]
type = custom/script
exec = echo "⏻"
interval = 0
click-left = ~/.config/polybar/scripts/rofi_powermenu.sh
label-font = 0
format-foreground = ${colors.red}
