[main]
# Modules to load
modules=time:input:powerbar

# Background image
background=/home/yhwach/.config/niri/blurred_wallpaper.jpg

# Blur
blur=0

# Style
style=/home/yhwach/.config/gtklock/style.css